### ISSUE TITLE
rtg-tools: sha1 deprecation warnings 

### ISSUE THREAD

**Issue by heuermh** [chapmanb/homebrew-cbl#32]
```bash
$ brew update
Updated Homebrew from a70c60b to 8e29cf1.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/chapmanb/homebrew-cbl/rtg-tools.rb:8:in `<class:RtgTools>'
Please report this to the chapmanb/cbl tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/chapmanb/homebrew-cbl/rtg-tools.rb:8:in `<class:RtgTools>'
Please report this to the chapmanb/cbl tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/chapmanb/homebrew-cbl/rtg-tools.rb:8:in `<class:RtgTools>'
Please report this to the chapmanb/cbl tap!
```

**Comment by heuermh** [comment]
Thank you, @Lenbok!
