### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by yzhzu** [chapmanb/homebrew-cbl#33]
brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in <class:BcbioRnaseq>' Please report this to the chapmanb/cbl tap! Please report this bug: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting /home/rcmm/.linuxbrew/Library/Homebrew/utils.rb:86:inodeprecated'
/home/rcmm/.linuxbrew/Library/Homebrew/utils.rb:94:in odisabled' /home/rcmm/.linuxbrew/Library/Homebrew/compat/sha1.rb:3:insha1'
/home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in <class:BcbioRnaseq>' /home/rcmm/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:3:inload_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:25:in module_eval' /home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:25:inload_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:42:in load_formula_from_path' /home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:97:inload_file'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:88:in klass' /home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:84:inget_formula'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:201:in get_formula' /home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:241:infactory'
/home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:272:in from_keg' /home/rcmm/.linuxbrew/Library/Homebrew/formulary.rb:255:infrom_rack'
/home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1364:in block in installed' /home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1362:inmap'
/home/rcmm/.linuxbrew/Library/Homebrew/formula.rb:1362:in installed' /home/rcmm/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:37:inupgrade'
/home/rcmm/.linuxbrew/Library/Homebrew/brew.rb:94:in

**Comment by chapmanb** [comment]
Sorry about the issue -- it looks like Homebrew/Linuxbrew have migrated away from using sha1 and now force sha256. These recipes have fallen out of date as we don't use them regularly in CloudBioLinux/bcbio any longer. Please feel free to take any useful recipes and update them to work within other Taps like homebrew-science or happy to accept a PR here to fix these if you find the older recipes here useful.

**Comment by rchekaluk** [comment]
+1
I receive a similar failure when attempting to build using the following [recommended quickstart](https://github.com/chapmanb/cloudbiolinux/pull/242#issuecomment-277438206):
```
$ fab -H $host install_biolinux:flavor=ngs_pipeline_minimal
```

**Comment by chapmanb** [comment]
Sorry about the issues, the ngs_pipeline_minimal module should no longer be using Homebrew/Linuxbrew recipes. Would you be able to post the full error you're seeing so we can figure out how to disable this.

**Comment by rchekaluk** [comment]
```

DBG [config.py]: Using config file /tmp/DIR/cloudbio/../config/chef_recipes.yaml
INFO: Reading /tmp/DIR/cloudbio/../config/chef_recipes.yaml
DBG [shared.py]: Packages to install: 
DBG [config.py]: Using config file /tmp/DIR/cloudbio/../config/puppet_classes.yaml
INFO: Reading /tmp/DIR/cloudbio/../config/puppet_classes.yaml
DBG [shared.py]: Packages to install: 
DBG [config.py]: Using config file /tmp/DIR/cloudbio/../config/main.yaml
INFO: Meta-package information from /tmp/DIR/cloudbio/../config/main.yaml
- Packages: minimal,desktop,programming,distributed,documentation,libraries,amazon,python,r,ruby,perl,java,java_extras,erlang,haskell,databases,math,viz,web,bio_general,bio_search,bio_alignment,bio_nextgen,bio_sequencing,bio_annotation,bio_microarray,bio_visualization,bio_utils,phylogeny
- Libraries: perl-libs,python-libs,r-libs,ruby-libs
DBG [config.py]: Using config file /tmp/DIR/cloudbio/../config/packages-homebrew.yaml
INFO: Reading /tmp/DIR/cloudbio/../config/packages-homebrew.yaml
DBG [shared.py]: Packages to install: biointerchange,bcftools,cufflinks-binary,htslib,samtools,bamtools,biobambam,cramtools,fastqc,fastx_toolkit,qualimap,sambamba-binary,staden_io_lib,delly;--with-binary,freebayes,gatk-framework,lofreq,pindel,platypus-variant,rtg-tools,scalpel,snpeff,theta2,vardict,vcflib,vcftools,vep,wham,bowtie2,bwa,novoalign,rna-star,parallel

[FQDN] sudo: rm -rf dist
[FQDN] sudo: rm -rf build
[FQDN] sudo: rm -rf lib/*.egg-info
[FQDN] run: rm -rf /home/ubuntu/tmp/cloudbiolinux
[FQDN] run: echo $HOME
[FQDN] out: /home/ubuntu
[FQDN] out: 

[FQDN] run: mkdir -p '/home/ubuntu/tmp/cloudbiolinux'
[FQDN] run: git clone https://github.com/Homebrew/linuxbrew.git
[FQDN] out: Cloning into 'linuxbrew'...
[FQDN] out: remote: Counting objects: 353740, done.
[FQDN] out: Receiving objects:   0% (1/353740)   
[FQDN] out: Receiving objects: 100% (353740/353740), 67.96 MiB | 9.88 MiB/s, done.
[FQDN] out: Resolving deltas:   0% (0/267332)   
[FQDN] out: Resolving deltas: 100% (267332/267332), done.
[FQDN] out: Checking connectivity... done.
[FQDN] out: 

[FQDN] sudo: chown ubuntu /usr/local
[FQDN] sudo: chown ubuntu /usr/local/bin
[FQDN] sudo: chown ubuntu /usr/local/etc
[FQDN] sudo: chown ubuntu /usr/local/include
[FQDN] sudo: chown ubuntu /usr/local/lib
[FQDN] sudo: chown ubuntu /usr/local/sbin
[FQDN] sudo: chown ubuntu /usr/local/share
[FQDN] sudo: chown ubuntu /usr/local/share/java
[FQDN] sudo: chown ubuntu /usr/local/share/man
[FQDN] sudo: chown ubuntu /usr/local/share/man/man1
[FQDN] sudo: chown ubuntu /usr/local/share/doc
[FQDN] sudo: chown ubuntu /usr/local/lib/python2.7/site-packages
[FQDN] run: mv Library /usr/local
[FQDN] run: mv .git /usr/local
[FQDN] run: mv -f share/man/man1/brew.1 /usr/local/share/man/man1
[FQDN] run: mv -f bin/brew /usr/local/bin
[FQDN] run: rm -rf /home/ubuntu/tmp/cloudbiolinux
[FQDN] run: /usr/local/bin/brew tap
[FQDN] run: /usr/local/bin/brew --prefix
[FQDN] out: /usr/local
[FQDN] out: 

[FQDN] run: /usr/local/bin/brew update
[FQDN] out: ==> Homebrew has enabled anonymous aggregate user behaviour analytics.
[FQDN] out: Read the analytics documentation (and how to opt-out) here:
[FQDN] out:   http://docs.brew.sh/Analytics.html
[FQDN] out: 
[FQDN] out: ==> Tapping homebrew/core
[FQDN] out: Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
[FQDN] out: remote: Counting objects: 4208, done.
[FQDN] out: remote: Compressing objects:   0% (1/4058)   
[FQDN] out: remote: Compressing objects: 100% (4058/4058), done.
[FQDN] out: Receiving objects:   0% (1/4208)   
[FQDN] out: Receiving objects: 100% (4208/4208), 3.39 MiB | 0 bytes/s, done.
[FQDN] out: Resolving deltas:   0% (0/33)   
[FQDN] out: Resolving deltas: 100% (33/33), done.
[FQDN] out: Checking connectivity... done.
[FQDN] out: Tapped 4055 formulae (4,239 files, 10.7M)
[FQDN] out: Already up-to-date.
[FQDN] out: ==> Migrating HOMEBREW_REPOSITORY (please wait)...
[FQDN] out: ==> Migrated HOMEBREW_REPOSITORY to /usr/local/Homebrew!
[FQDN] out: Homebrew no longer needs to have ownership of /usr/local. If you wish you can
[FQDN] out: return /usr/local to its default ownership with:
[FQDN] out:   sudo chown root:wheel /usr/local
[FQDN] out: 

[FQDN] run: /usr/local/bin/brew tap
[FQDN] out: homebrew/core
[FQDN] out: 

[FQDN] run: /usr/local/bin/brew tap homebrew/science
[FQDN] out: ==> Tapping homebrew/science
[FQDN] out: Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science'...
[FQDN] out: remote: Counting objects: 684, done.
[FQDN] out: remote: Compressing objects:   0% (1/679)   
[FQDN] out: remote: Compressing objects: 100% (679/679), done.
[FQDN] out: Receiving objects:   0% (1/684)   
[FQDN] out: Receiving objects: 100% (684/684), 620.39 KiB | 0 bytes/s, done.
[FQDN] out: Checking connectivity... done.
[FQDN] out: Tapped 666 formulae (702 files, 2M)
[FQDN] out: 

[FQDN] run: /usr/local/bin/brew tap chapmanb/cbl
[FQDN] out: ==> Tapping chapmanb/cbl
[FQDN] out: Cloning into '/usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl'...
[FQDN] out: remote: Counting objects: 50, done.
[FQDN] out: remote: Compressing objects:   2% (1/49)   
[FQDN] out: remote: Compressing objects: 100% (49/49), done.
[FQDN] out: remote: Total 50 (delta 3), reused 18 (delta 1), pack-reused 0
[FQDN] out: Unpacking objects:   2% (1/50)   
[FQDN] out: Unpacking objects: 100% (50/50), done.
[FQDN] out: Checking connectivity... done.
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/isaac-variant-caller.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/isaac-variant-caller.rb:7:in `<class:IsaacVariantCaller>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/qsnp.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/qsnp.rb:7:in `<class:Qsnp>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb:7:in `<class:MetalGwas>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb:7:in `<class:Rsem>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/s3gof3r.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/s3gof3r.rb:11:in `<class:S3gof3r>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/vt.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/vt.rb:7:in `<class:Vt>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/lofreq.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/lofreq.rb:11:in `<class:Lofreq>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb:7:in `<class:Caveman>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/isaac-aligner.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/isaac-aligner.rb:7:in `<class:IsaacAligner>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cufflinks-binary.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cufflinks-binary.rb:11:in `<class:CufflinksBinary>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/seqbuster.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/seqbuster.rb:6:in `<class:Seqbuster>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb:7:in `<class:Scalpel>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/theta2.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/theta2.rb:7:in `<class:Theta2>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/speedseq.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/speedseq.rb:7:in `<class:Speedseq>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb:7:in `<class:Cramtools>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/gvcftools.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/gvcftools.rb:7:in `<class:Gvcftools>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/bwakit.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/bwakit.rb:7:in `<class:Bwakit>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/flux-simulator.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/flux-simulator.rb:7:in `<class:FluxSimulator>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/bcbio-rnaseq.rb:7:in `<class:BcbioRnaseq>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/impute2.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/impute2.rb:11:in `<class:Impute2>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/oncofuse.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/oncofuse.rb:7:in `<class:Oncofuse>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/staden_io_lib.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/staden_io_lib.rb:7:in `<class:StadenIoLib>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cancerit-allelecount.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/cancerit-allelecount.rb:7:in `<class:CanceritAllelecount>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/qsignature.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/qsignature.rb:7:in `<class:Qsignature>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb:7:in `<class:Libmaus>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/express-binary.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/express-binary.rb:11:in `<class:ExpressBinary>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Invalid formula: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb
[FQDN] out: Calling Formula.sha1 is disabled!
[FQDN] out: Use Formula.sha256 instead.
[FQDN] out: /usr/local/Homebrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb:7:in `<class:Pindel>'
[FQDN] out: Please report this to the chapmanb/cbl tap!
[FQDN] out: Error: Cannot tap chapmanb/cbl: invalid syntax in tap!
[FQDN] out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: /usr/local/bin/brew tap chapmanb/cbl
Executed: /bin/bash -i -c "/usr/local/bin/brew tap chapmanb/cbl"

Aborting.

Disconnecting from FQDN... done.
```

**Comment by chapmanb** [comment]
Thanks for the full traceback. This looks like the install is using the default set of parameters instead of the `ngs_pipeline_minimal` one, which leads to the issue. You're right that it won't work right now with that setup as the main `packages-homebrew.yaml` uses these out of data packages. Is it possible your run doesn't use the flavor parameter or has something else different.

I tested out and improved the quick start documentation to bootstrap on a bare machine with conda:

https://github.com/chapmanb/cloudbiolinux#quick-start

I hope following that will lead to a cleaner experience. Please let me know if you run into any issues with this and happy to debug more.

**Comment by rchekaluk** [comment]
Sorry, user error: building ngs_pipeline_minimal works as advertised. Sorry for the noise.
